name: Deploy to Azure VM

on:
  workflow_run:
    workflows: ["Build and push images to DockerHub"]
    types: [completed]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ ithub.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}

    steps:
      - name: Checkout repo (to get docker-compose.yml)
        uses: actions/checkout@v4

      - name: Copy docker-compose.yml to VM
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          source: "docker-compose.yml"
          target: "/home/${{ secrets.VM_USER }}/super-app"

      - name: Deploy via SSH (docker compose up)
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            set -e
            cd ~/super-app
            sudo docker compose pull
            sudo docker compose up -d --remove-orphans
            sudo docker compose ps
